// <auto-generated />
using System;
using Casha.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Casha.DAL.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20221213213959_AddedRecipesSeeding")]
    partial class AddedRecipesSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Casha.Core.DbModels.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryType")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Ukrainian",
                            CategoryType = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Italian",
                            CategoryType = 1
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "French",
                            CategoryType = 1
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "English",
                            CategoryType = 1
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Japanese",
                            CategoryType = 1
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Chinese",
                            CategoryType = 1
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Korean",
                            CategoryType = 1
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "New Year",
                            CategoryType = 0
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Easter",
                            CategoryType = 0
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Thanksgiving",
                            CategoryType = 0
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Christmas",
                            CategoryType = 0
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Birthday",
                            CategoryType = 0
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Swedish",
                            CategoryType = 1
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Thai",
                            CategoryType = 1
                        });
                });

            modelBuilder.Entity("Casha.Core.DbModels.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"), 1L, 1);

                    b.Property<string>("CommentBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Casha.Core.DbModels.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Casha.Core.DbModels.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Name = "Grapefruit"
                        },
                        new
                        {
                            ProductId = 2,
                            Name = "Salt"
                        },
                        new
                        {
                            ProductId = 3,
                            Name = "Black pepper"
                        },
                        new
                        {
                            ProductId = 4,
                            Name = "Chicken"
                        },
                        new
                        {
                            ProductId = 5,
                            Name = "Parsley"
                        },
                        new
                        {
                            ProductId = 6,
                            Name = "Bacon"
                        },
                        new
                        {
                            ProductId = 7,
                            Name = "Olive oil"
                        },
                        new
                        {
                            ProductId = 8,
                            Name = "Cognak"
                        },
                        new
                        {
                            ProductId = 9,
                            Name = "Cream"
                        },
                        new
                        {
                            ProductId = 10,
                            Name = "White rice"
                        },
                        new
                        {
                            ProductId = 11,
                            Name = "Water"
                        },
                        new
                        {
                            ProductId = 12,
                            Name = "Rice vinegar"
                        },
                        new
                        {
                            ProductId = 13,
                            Name = "Vegetable oil"
                        },
                        new
                        {
                            ProductId = 14,
                            Name = "White sugar"
                        },
                        new
                        {
                            ProductId = 15,
                            Name = "Butter"
                        },
                        new
                        {
                            ProductId = 16,
                            Name = "Flour"
                        },
                        new
                        {
                            ProductId = 17,
                            Name = "Milk"
                        },
                        new
                        {
                            ProductId = 18,
                            Name = "Species"
                        },
                        new
                        {
                            ProductId = 19,
                            Name = "Spinach"
                        },
                        new
                        {
                            ProductId = 20,
                            Name = "Salmon fillet"
                        },
                        new
                        {
                            ProductId = 21,
                            Name = "Double cream"
                        },
                        new
                        {
                            ProductId = 22,
                            Name = "Risotto rice"
                        },
                        new
                        {
                            ProductId = 23,
                            Name = "Chicken stock"
                        },
                        new
                        {
                            ProductId = 24,
                            Name = "Pesto"
                        },
                        new
                        {
                            ProductId = 25,
                            Name = "Goat's cheese"
                        },
                        new
                        {
                            ProductId = 26,
                            Name = "Thai green curry paste"
                        },
                        new
                        {
                            ProductId = 27,
                            Name = "Coconut milk"
                        },
                        new
                        {
                            ProductId = 28,
                            Name = "Prawns"
                        },
                        new
                        {
                            ProductId = 29,
                            Name = "Courgetti"
                        },
                        new
                        {
                            ProductId = 30,
                            Name = "Lamb"
                        },
                        new
                        {
                            ProductId = 31,
                            Name = "Onion"
                        },
                        new
                        {
                            ProductId = 32,
                            Name = "Thyme"
                        },
                        new
                        {
                            ProductId = 33,
                            Name = "Red wine"
                        },
                        new
                        {
                            ProductId = 34,
                            Name = "Watercress"
                        },
                        new
                        {
                            ProductId = 35,
                            Name = "Feta"
                        },
                        new
                        {
                            ProductId = 36,
                            Name = "Self-raising flour"
                        },
                        new
                        {
                            ProductId = 37,
                            Name = "Sparkling water"
                        },
                        new
                        {
                            ProductId = 38,
                            Name = "Groundnut oil"
                        });
                });

            modelBuilder.Entity("Casha.Core.DbModels.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"), 1L, 1);

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipeImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            Difficulty = 1,
                            Instruction = "Working over a bowl to collect juice, section grapefruits into suprêmes, cutting away all peel, pith, and membranes. Squeeze remaining skin and membranes into the bowl to extract as much juice as possible.\r\n\r\nPreheat the oven to 375 degrees F (190 degrees C).\r\n\r\nStir together salt and pepper in a small bowl. Slip fingers beneath the skin of the chicken breast and thighs to loosen it from the meat. Rub salt mixture under skin, inside cavity, and over skin. Tuck half the suprêmes and a few parsley sprigs into chicken cavity. Transfer chicken, breast side up, to a rack in a baking dish or a cast-iron skillet.\r\n\r\nTie legs together with kitchen twine; fold wing tips back and tuck under chicken. Halve bacon; drape over breast in a herringbone pattern, overlapping as needed. Drizzle with oil, coating any uncovered skin.\r\n\r\nRoast in the preheated oven for 40 minutes. Pour grapefruit juice over chicken. Continue roasting 35 to 40 minutes or until an instant-read thermometer inserted into thickest parts of thigh and breast registers 170°F. Tent with foil; let rest at least 15 minutes. Discard kitchen twine. Remove and reserve suprêmes from chicken cavity.\r\n\r\nFor sauce, warm cognac in a small stainless-steel or copper (not nonstick) skillet over medium heat for a few seconds until shimmering at the edges. Remove from heat.\r\n\r\nCarefully ignite with a stick lighter or long match. Let burn for 1 minute. Add roasted grapefruit suprêmes, the broth, and half-and-half; heat through. Season to taste with salt and pepper.\r\n\r\nServe chicken on a platter with remaining fresh suprêmes (or extra grapefruit wedges) and parsley sprigs. Spoon warm sauce over carved chicken.",
                            Name = "Roast Chicken with Grapefruit",
                            RecipeImageUrl = "string",
                            UserId = "b74ddd14-6340-4840-95c2-db12554843e5"
                        },
                        new
                        {
                            RecipeId = 2,
                            Difficulty = 0,
                            Instruction = "Rinse the rice in a strainer or colander under cold running water until the water runs clear.\r\n\r\nCombine rice and water in a saucepan over medium-high heat and bring to a boil. Reduce heat to low, cover, and cook until rice is tender and all water has been absorbed, about 20 minutes. Remove from stove and set aside until cool enough to handle.\r\n\r\nMeanwhile, combine rice vinegar, oil, sugar, and salt in a small saucepan over medium heat. Cook until the sugar has dissolved. Allow to cool, then stir into the cooked rice. While mixture will appear very wet at first, keep stirring and rice will dry as it cools.",
                            Name = "Perfect Sushi Rice",
                            RecipeImageUrl = "string",
                            UserId = "b74ddd14-6340-4840-95c2-db12554843e5"
                        },
                        new
                        {
                            RecipeId = 3,
                            Difficulty = 0,
                            Instruction = "Melt butter in a large saucepan over medium heat. Add flour and whisk into the melted butter until smooth. Cook and stir until flour turns a light, golden, sandy color, about 7 minutes.\r\n\r\nIncrease heat to medium-high and slowly whisk in milk until thickened by the roux. Bring to a gentle simmer, then reduce heat to medium-low and continue simmering until the flour has softened and no longer tastes gritty, 10 to 20 minutes. Season with salt and species.",
                            Name = "Bechamel sause",
                            RecipeImageUrl = "string",
                            UserId = "b74ddd14-6340-4840-95c2-db12554843e5"
                        },
                        new
                        {
                            RecipeId = 4,
                            Difficulty = 0,
                            Instruction = "STEP 1\r\nPut the spinach in a really big saucepan (or two saucepans) and add a few tablespoons of water. Cover, set over a medium heat and cook for about 5-8 mins, turning the spinach over every so often, until wilted. Tip it into a colander to drain and allow it to cool (spread it out on a plate to cool it quicker). Take big handfuls of it in your fists and squeeze out the excess water. It’s really important that you do this, otherwise the water will leach out and make the cream watery and green.\r\n\r\nSTEP 2\r\nChop the spinach. Melt the butter in a saucepan and gently toss the spinach in it. Season with pepper and a tiny bit of salt (there’s so much salt in the salmon). Heat the oven to 160C/140C fan/gas 3. Lay the spinach in the bottom of a gratin dish (about 30cm x 20cm), then arrange the salmon fillets on top.\r\n\r\nSTEP 3\r\nHeat the double cream in a small pan, then pour it all over the salmon and spinach. Bake for 35 mins, or until the top is golden and the cream is bubbling.",
                            Name = "Smoked salmon & spinach gratin",
                            RecipeImageUrl = "string",
                            UserId = "b74ddd14-6340-4840-95c2-db12554843e5"
                        },
                        new
                        {
                            RecipeId = 5,
                            Difficulty = 0,
                            Instruction = "STEP 1\r\nPour a glug of olive oil into a large saucepan. Tip in the rice and fry for 1 min. Add half the stock and cook until absorbed. Add the remaining stock, a ladle at a time, and cook until the rice is al dente, stirring continually, for 20-25 mins.\r\n\r\nSTEP 2\r\nStir through the pesto and half the goat’s cheese. Serve topped with the remaining cheese.",
                            Name = "Pesto & goat's cheese risotto",
                            RecipeImageUrl = "string",
                            UserId = "b74ddd14-6340-4840-95c2-db12554843e5"
                        },
                        new
                        {
                            RecipeId = 6,
                            Difficulty = 0,
                            Instruction = "Heat 1 tsp flavourless oil in a frying pan over a medium heat. Add the curry paste and cook for 1 min. Pour in the coconut milk, then leave to bubble away for a few mins before adding the prawns and courgetti. Cook for 1 min more to warm through, then divide between bowls.",
                            Name = "Prawn & coconut soup",
                            RecipeImageUrl = "string",
                            UserId = "b74ddd14-6340-4840-95c2-db12554843e5"
                        },
                        new
                        {
                            RecipeId = 7,
                            Difficulty = 0,
                            Instruction = "STEP 1\r\nFirstly, prepare the lamb. Heat oven to 160C/fan140C/gas 3. Wipe the meat all over and season well. Heat 3 tbsp of olive oil in a large heavy flameproof casserole, add the meat and fry all over on a fairly high heat for about 8 mins, turning until it is evenly well browned. Remove to a plate.\r\n\r\nSTEP 2\r\nThinly slice the onions. Add to the pan and fry for about 10 mins, until softened and tinged with brown. Add a few of the thyme sprigs and cook for a further minute or so. Season with salt and pepper.\r\n\r\nSTEP 3\r\nSit the lamb on top of the onions, then add the wine. Cover tightly. Bake for 3 hrs. You can make to this stage up to 2 days in advance, then reheat for 45 mins.\r\n\r\nSTEP 4\r\nTo finish off, strip the leaves from 2 thyme sprigs and chop them with the parsley. Scatter over before serving.",
                            Name = "Slow-cooked lamb with onions & thyme",
                            RecipeImageUrl = "string",
                            UserId = "b74ddd14-6340-4840-95c2-db12554843e5"
                        },
                        new
                        {
                            RecipeId = 8,
                            Difficulty = 0,
                            Instruction = "STEP 1\r\nHeat oven to 200C/180C fan/ gas 6 and roast the salmon for 8 mins. Meanwhile, segment the grapefruit and mix the juices with 2 tbsp extra virgin olive oil to make a dressing.\r\n\r\nSTEP 2\r\nToss the watercress with the grapefruit segments, dressing and feta, and serve with the salmon, flaked into large pieces.",
                            Name = "Citrus salmon salad",
                            RecipeImageUrl = "string",
                            UserId = "b74ddd14-6340-4840-95c2-db12554843e5"
                        },
                        new
                        {
                            RecipeId = 9,
                            Difficulty = 0,
                            Instruction = "STEP 1\r\nUse a fork to steady your onion. Slice the onion into rings about 1cm wide. Remove the skin and separate the rings.\r\n\r\nSTEP 2\r\nHeat the oil to 180C in a heavy-based pan – it should be no more than 1/ 3 full.\r\n\r\nSTEP 3\r\nMeanwhile put the flour and sparkling water in a bowl and season generously. Whisk together to form a batter.\r\n\r\nSTEP 4\r\nCoat a small batch of onion rings in batter. Carefully lower into the hot oil and deep-fry until crisp and golden, about 2 - 3 minutes. Remove with a slotted spoon and place on a piece of kitchen towel to drain. Repeat with the remaining onion and batter.",
                            Name = "Onion rings",
                            RecipeImageUrl = "string",
                            UserId = "b74ddd14-6340-4840-95c2-db12554843e5"
                        });
                });

            modelBuilder.Entity("Casha.Core.DbModels.RecipeCategory", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("RecipeId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("RecipeCategories");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            CategoryId = 4
                        },
                        new
                        {
                            RecipeId = 1,
                            CategoryId = 11
                        },
                        new
                        {
                            RecipeId = 2,
                            CategoryId = 5
                        },
                        new
                        {
                            RecipeId = 3,
                            CategoryId = 2
                        },
                        new
                        {
                            RecipeId = 4,
                            CategoryId = 13
                        },
                        new
                        {
                            RecipeId = 5,
                            CategoryId = 2
                        },
                        new
                        {
                            RecipeId = 6,
                            CategoryId = 14
                        },
                        new
                        {
                            RecipeId = 7,
                            CategoryId = 4
                        },
                        new
                        {
                            RecipeId = 8,
                            CategoryId = 3
                        },
                        new
                        {
                            RecipeId = 9,
                            CategoryId = 4
                        });
                });

            modelBuilder.Entity("Casha.Core.DbModels.RecipeProduct", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("RecipeId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("RecipeProducts");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            ProductId = 1,
                            Quantity = 3.0,
                            Unit = 4
                        },
                        new
                        {
                            RecipeId = 1,
                            ProductId = 2,
                            Quantity = 1.0,
                            Unit = 1
                        },
                        new
                        {
                            RecipeId = 1,
                            ProductId = 3,
                            Quantity = 1.5,
                            Unit = 0
                        },
                        new
                        {
                            RecipeId = 1,
                            ProductId = 4,
                            Quantity = 1.0,
                            Unit = 4
                        },
                        new
                        {
                            RecipeId = 1,
                            ProductId = 5,
                            Quantity = 25.0,
                            Unit = 2
                        },
                        new
                        {
                            RecipeId = 1,
                            ProductId = 6,
                            Quantity = 150.0,
                            Unit = 2
                        },
                        new
                        {
                            RecipeId = 1,
                            ProductId = 7,
                            Quantity = 1.0,
                            Unit = 1
                        },
                        new
                        {
                            RecipeId = 1,
                            ProductId = 8,
                            Quantity = 1.0,
                            Unit = 1
                        },
                        new
                        {
                            RecipeId = 1,
                            ProductId = 9,
                            Quantity = 1.0,
                            Unit = 0
                        },
                        new
                        {
                            RecipeId = 2,
                            ProductId = 10,
                            Quantity = 400.0,
                            Unit = 2
                        },
                        new
                        {
                            RecipeId = 2,
                            ProductId = 11,
                            Quantity = 750.0,
                            Unit = 2
                        },
                        new
                        {
                            RecipeId = 2,
                            ProductId = 12,
                            Quantity = 4.0,
                            Unit = 1
                        },
                        new
                        {
                            RecipeId = 2,
                            ProductId = 13,
                            Quantity = 1.0,
                            Unit = 1
                        },
                        new
                        {
                            RecipeId = 2,
                            ProductId = 14,
                            Quantity = 2.0,
                            Unit = 1
                        },
                        new
                        {
                            RecipeId = 2,
                            ProductId = 3,
                            Quantity = 1.0,
                            Unit = 0
                        },
                        new
                        {
                            RecipeId = 3,
                            ProductId = 15,
                            Quantity = 5.0,
                            Unit = 1
                        },
                        new
                        {
                            RecipeId = 3,
                            ProductId = 16,
                            Quantity = 4.0,
                            Unit = 1
                        },
                        new
                        {
                            RecipeId = 3,
                            ProductId = 17,
                            Quantity = 300.0,
                            Unit = 3
                        },
                        new
                        {
                            RecipeId = 3,
                            ProductId = 3,
                            Quantity = 1.0,
                            Unit = 0
                        },
                        new
                        {
                            RecipeId = 3,
                            ProductId = 18,
                            Quantity = 0.25,
                            Unit = 0
                        },
                        new
                        {
                            RecipeId = 4,
                            ProductId = 19,
                            Quantity = 1200.0,
                            Unit = 2
                        },
                        new
                        {
                            RecipeId = 4,
                            ProductId = 15,
                            Quantity = 15.0,
                            Unit = 2
                        },
                        new
                        {
                            RecipeId = 4,
                            ProductId = 20,
                            Quantity = 1000.0,
                            Unit = 2
                        },
                        new
                        {
                            RecipeId = 4,
                            ProductId = 21,
                            Quantity = 300.0,
                            Unit = 3
                        },
                        new
                        {
                            RecipeId = 5,
                            ProductId = 7,
                            Quantity = 20.0,
                            Unit = 2
                        },
                        new
                        {
                            RecipeId = 5,
                            ProductId = 22,
                            Quantity = 200.0,
                            Unit = 2
                        },
                        new
                        {
                            RecipeId = 5,
                            ProductId = 23,
                            Quantity = 700.0,
                            Unit = 3
                        },
                        new
                        {
                            RecipeId = 5,
                            ProductId = 24,
                            Quantity = 250.0,
                            Unit = 2
                        },
                        new
                        {
                            RecipeId = 5,
                            ProductId = 25,
                            Quantity = 100.0,
                            Unit = 2
                        },
                        new
                        {
                            RecipeId = 6,
                            ProductId = 26,
                            Quantity = 3.0,
                            Unit = 1
                        },
                        new
                        {
                            RecipeId = 6,
                            ProductId = 27,
                            Quantity = 400.0,
                            Unit = 3
                        },
                        new
                        {
                            RecipeId = 6,
                            ProductId = 28,
                            Quantity = 150.0,
                            Unit = 2
                        },
                        new
                        {
                            RecipeId = 6,
                            ProductId = 29,
                            Quantity = 250.0,
                            Unit = 2
                        },
                        new
                        {
                            RecipeId = 7,
                            ProductId = 30,
                            Quantity = 1250.0,
                            Unit = 2
                        },
                        new
                        {
                            RecipeId = 7,
                            ProductId = 31,
                            Quantity = 1000.0,
                            Unit = 2
                        },
                        new
                        {
                            RecipeId = 7,
                            ProductId = 32,
                            Quantity = 30.0,
                            Unit = 2
                        },
                        new
                        {
                            RecipeId = 7,
                            ProductId = 33,
                            Quantity = 300.0,
                            Unit = 3
                        },
                        new
                        {
                            RecipeId = 7,
                            ProductId = 5,
                            Quantity = 30.0,
                            Unit = 2
                        },
                        new
                        {
                            RecipeId = 8,
                            ProductId = 20,
                            Quantity = 2.0,
                            Unit = 4
                        },
                        new
                        {
                            RecipeId = 8,
                            ProductId = 1,
                            Quantity = 1.0,
                            Unit = 4
                        },
                        new
                        {
                            RecipeId = 8,
                            ProductId = 34,
                            Quantity = 100.0,
                            Unit = 2
                        },
                        new
                        {
                            RecipeId = 8,
                            ProductId = 35,
                            Quantity = 200.0,
                            Unit = 2
                        },
                        new
                        {
                            RecipeId = 9,
                            ProductId = 31,
                            Quantity = 1.0,
                            Unit = 4
                        },
                        new
                        {
                            RecipeId = 9,
                            ProductId = 38,
                            Quantity = 150.0,
                            Unit = 3
                        },
                        new
                        {
                            RecipeId = 9,
                            ProductId = 36,
                            Quantity = 150.0,
                            Unit = 2
                        },
                        new
                        {
                            RecipeId = 9,
                            ProductId = 37,
                            Quantity = 180.0,
                            Unit = 3
                        });
                });

            modelBuilder.Entity("Casha.Core.DbModels.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCertified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b74ddd14-6340-4840-95c2-db12554843e5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3a593ddb-abaa-418d-89ad-56366e8cebba",
                            DisplayName = "admin",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "admin",
                            IsCertified = true,
                            LastName = "admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAECrubOlwsbAqioDfrp6R3iCtmmWkypW24pVfwxbOXrLwBkl5Mb1P/ovlhiyTGw3UAw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b126b7f4-ab32-431b-8c1e-cf7b85f82baf",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        });
                });

            modelBuilder.Entity("Casha.Core.DbModels.UserProduct", b =>
                {
                    b.Property<int>("UserProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserProductId"), 1L, 1);

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserProductId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("UserProducts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "fab4fac1-c546-41de-aebc-a14da6895711",
                            ConcurrencyStamp = "1",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            ConcurrencyStamp = "2",
                            Name = "User",
                            NormalizedName = "User"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "b74ddd14-6340-4840-95c2-db12554843e5",
                            RoleId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Casha.Core.DbModels.Comment", b =>
                {
                    b.HasOne("Casha.Core.DbModels.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Casha.Core.DbModels.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Casha.Core.DbModels.Post", b =>
                {
                    b.HasOne("Casha.Core.DbModels.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Casha.Core.DbModels.Recipe", b =>
                {
                    b.HasOne("Casha.Core.DbModels.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Casha.Core.DbModels.RecipeCategory", b =>
                {
                    b.HasOne("Casha.Core.DbModels.Category", "Category")
                        .WithMany("RecipeCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Casha.Core.DbModels.Recipe", "Recipe")
                        .WithMany("RecipeCategories")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Casha.Core.DbModels.RecipeProduct", b =>
                {
                    b.HasOne("Casha.Core.DbModels.Product", "Product")
                        .WithMany("RecipeProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Casha.Core.DbModels.Recipe", "Recipe")
                        .WithMany("RecipeProducts")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Casha.Core.DbModels.UserProduct", b =>
                {
                    b.HasOne("Casha.Core.DbModels.Product", "Product")
                        .WithMany("UserProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Casha.Core.DbModels.User", "User")
                        .WithMany("UserProducts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Casha.Core.DbModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Casha.Core.DbModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Casha.Core.DbModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Casha.Core.DbModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Casha.Core.DbModels.Category", b =>
                {
                    b.Navigation("RecipeCategories");
                });

            modelBuilder.Entity("Casha.Core.DbModels.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Casha.Core.DbModels.Product", b =>
                {
                    b.Navigation("RecipeProducts");

                    b.Navigation("UserProducts");
                });

            modelBuilder.Entity("Casha.Core.DbModels.Recipe", b =>
                {
                    b.Navigation("RecipeCategories");

                    b.Navigation("RecipeProducts");
                });

            modelBuilder.Entity("Casha.Core.DbModels.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Posts");

                    b.Navigation("Recipes");

                    b.Navigation("UserProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
